### PR TITLE
#232 - allow N-dimensional images

### PR DESCRIPTION
**Pull request by AlecThomson**
A simple fix for #232

### CODE REVIEW

**Comment by cjordan** [comment]
Hi @AlecThomson. Thanks for the PR, it looks good. I appreciate that you're new to Rust, however, would it be possible for you to write some tests alongside this code? I am happy to help and offer guidance if you need it.

**Comment by AlecThomson** [comment]
Thanks @cjordan! I've just put in some really simple tests - just checking dimensionality and indexing with some dummy data. I hope these are in the right places - let me now if there are any other tweaks or additions we should put in.

**Comment by cjordan** [comment]
Thanks for turning that around so quickly! I think those also look good, but I'll let @simonrw have a look.

It occurs to me now that the actual code for determine the shape could be a little better; if so, I'll also push to this branch in a moment.

**Comment by cjordan** [comment]
Nope, disregard, I think the code is good as is (I was hoping to remove the additional `shape` allocation).

I see you're also in Perth doing astronomy. What a small world. I'm heavily utilising Rust for MWA stuff. Let me know if you want to chat about it or whatever -- I personally think we should do all new backend projects in Rust.

**Comment by simonrw** [comment]
Hey thanks for submitting this and the corresponding issue! I'm happy to see this crate reach a wider audience. 

The changes look great, thanks. I'll merge this and do a release when I get a chance. Until then you may have to use the `main` git branch.

**Comment by simonrw** [comment]
@AlecThomson I've released version 0.21.2 which includes your PR. Thanks for this contribution! :tada:

**Comment by cjordan** [comment]
Thanks for doing the dirty work, @simonrw

**Pull request merged**
