### PR TITLE
Support creating fitsfiles from raw pointers

### LINKED ISSUE #194: Opening FITS-files from memory
My program receives FITS file from [INDI server](https://indilib.org/develop/developer-manual/92-indi-server.html). I need functionality to open FITS files directly from memory without writing to disk. Is this possible for cfitsio and rust-fitsio?

### PR DESCRIPTION
**Pull request by simonrw**
Closes #194

### CODE REVIEW

**Comment by cjordan** [comment]
I haven't run the code myself, but I trust that it works, and it looks fine to me.  My only real comment is to do with the mandatory `filename` field of the `FitsFile` struct; it's a nitpick, but strictly speaking it shouldn't be necessary for the new method.  The situation could be "fixed" by making the `filename` field optional, and the new method has an `filename: Option<impl AsRef<Path>>` field. However, this doesn't sit with me 100% well (I guess I find optional arguments a little untidy), so you could just ignore this nitpick and proceed :slightly_smiling_face:

**Comment by simonrw** [comment]
>   I haven't run the code myself, but I trust that it works, and it looks fine to me.  My only real comment is to do with the mandatory `filename` field of the `FitsFile` struct; it's a nitpick, but strictly speaking it shouldn't be necessary for the new method.  The situation could be "fixed" by making the `filename` field optional, and the new method has an `filename: Option<impl AsRef<Path>>` field. However, this doesn't sit with me 100% well (I guess I find optional arguments a little untidy), so you could just ignore this nitpick and proceed 🙂

Thanks for pointing this out. I hadn't really considered that, nor that the filename is actually optional for the `FitsFile` struct.

I think we can get away without needing the optional filename for opening/creating a disk-backed file. dabece58afed4c729a68507c063f84cb83b1e302 shows how we can require the field for `create`/`open`/`edit`, and not require it for `from_raw`. It's optional for `FitsFile` but it's not currently used. We only really use it for printing which I expect to be a niche feature. We may even want to make the property non-`pub` to emphasise that the user shouldn't really care, or more accurately: they should keep track of the filename themselves.

**Update**: I've done this in a new commit 3342d16386b34136f93a70928fecbbc42ce50108...

**Comment by simonrw** [comment]
I think I'll merge this, but I'll write up a changelog entry first. Hopefully nobody is depending on the `FitsFile.filename` field...

**Comment by cjordan** [comment]
Your changes match what I would've done!  Looks good.  I didn't spot that `filename` was a public field, but I'd argue that it should not be; being public means someone could change it, and while in this case it wouldn't do anything bad, it's better IMO to not make this possible to prevent someone even considering it.

Just a friendly reminder that we're using `rust-fitsio` across all our archive at the MWA collaboration, processing tens of petabytes!

**Comment by simonrw** [comment]
That's awesome, glad to hear the crate is being battle tested!

**Pull request merged**
