### PR TITLE
Added `write_key_cmt` method to include comments with keys.

### PR DESCRIPTION
**Pull request by sunipkm**
I have added a function `write_key_cmt` to allow the addition of comments along with the key.

### CODE REVIEW

**Review by simonrw — COMMENTED** [review]
Hi, thanks for raising this PR. I really appreciate it when people are using this crate!

I have a concern about the API. I would really not like to add too many methods to the public API.

Some options I considered:
1. make the `write_key` method take an optional comment
  * the downside is the user will have to explicitly pass `None` if they don't care about the comment
  * an upside is it might get people to think more meaningfully about writing fits comments, even though they are restricted in length which is a pain to use
2. make the `write_key` methods use the builder pattern, where they return a builder object with a `.write()` method to actually perform the write, and can include a `with_comment` method to add a comment
  * this could be quite verbose
  * builder patterns are great for types with _many_ fields, but there is only one extra field here really so it could be overkill
3. keep your implementation
  * adds almost duplicate methods to do nearly the same thing
  * its what a C API design might look like, rather than a Rust API
4. Make the write key methods generic over a trait that's implemented by a simple value, or a couple of value string pairs.
4. ???

I am open to suggestions here. We are still pre-1.0 so we could always change our minds in the future. I am personally siding with option 4.

Also: this PR supports writing comments with keys, but it might be nice to be able to _read_ comments as well. I don't mind this being a follow up PR, but I think we should add that functionality, once we have settled on a nice API.

**Comment by sunipkm** [comment]
The only issue I see with 1 or 2 is that it’s going to be API breaking, which is something I wanted to avoid. I do agree that my implementation is very C-like. I do like the idea of a generic trait, that’s more Rust-like. I will give this a bit more thought. 

I agree that we should be able to read the comments as well. 

Will you ever consider a pure Rust implementation of FITSIO?

**Comment by simonrw** [comment]
> The only issue I see with 1 or 2 is that it’s going to be API breaking, which is something I wanted to avoid. I do agree that my implementation is very C-like. I do like the idea of a generic trait, that’s more Rust-like. I will give this a bit more thought.

**Comment by simonrw** [comment]
I've drafted my new API design in https://github.com/simonrw/rust-fitsio/pull/332, let me know what you think

**Comment by simonrw** [comment]
Thanks for this contribution, but as discussed We are going with the implementation from #332

**Pull request closed without merging**
